trigger:
 - main

pool:
   vmImage: 'ubuntu-latest' 
   name: default

variables:
   imageName: 'pipelines-javascript-docker'
   # https://github.com/moby/buildkit introduces build improvements around performance, storage management, feature functionality, and security. BuildKit currently isn't supported on Windows hosts.
   DOCKER_BUILDKIT: 1

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile